/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as SignInRouteImport } from './sign-in'
import { Route as AuthedRouteImport } from './_authed'
import { Route as AuthedIndexRouteImport } from './_authed.index'
import { Route as AuthedUserRouteImport } from './_authed.user'
import { Route as AuthedTaskIndexRouteImport } from './_authed.task.index'
import { Route as AuthedTaskIdRouteImport } from './_authed.task.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTaskIndexRoute = AuthedTaskIndexRouteImport.update({
  id: '/task/',
  path: '/task/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTaskIdRoute = AuthedTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/user': typeof AuthedUserRoute
  '/task/$id': typeof AuthedTaskIdRoute
  '/task/': typeof AuthedTaskIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/user': typeof AuthedUserRoute
  '/': typeof AuthedIndexRoute
  '/task/$id': typeof AuthedTaskIdRoute
  '/task': typeof AuthedTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/user': typeof AuthedUserRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/task/$id': typeof AuthedTaskIdRoute
  '/_authed/task/': typeof AuthedTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/user' | '/task/$id' | '/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/user' | '/' | '/task/$id' | '/task'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/user'
    | '/_authed/'
    | '/_authed/task/$id'
    | '/_authed/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/user': {
      id: '/_authed/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/task/': {
      id: '/_authed/task/'
      path: '/task'
      fullPath: '/task/'
      preLoaderRoute: typeof AuthedTaskIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/task/$id': {
      id: '/_authed/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof AuthedTaskIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedUserRoute: typeof AuthedUserRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedTaskIdRoute: typeof AuthedTaskIdRoute
  AuthedTaskIndexRoute: typeof AuthedTaskIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUserRoute: AuthedUserRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedTaskIdRoute: AuthedTaskIdRoute,
  AuthedTaskIndexRoute: AuthedTaskIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
